#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V

bspc config border_width 5
bspc config focused_border_color \#03fca1
bspc config normal_border_color \#cba6f7
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config top_padding 45
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

wmname LG3D

# Autostart
picom --config $HOME/.config/bspwm/picom.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
onedriver &
blueman-applet &
nitrogen --restore  
numlockx on &
$HOME/.config/polybar/launch.sh &