color0 #1b1017
color1 #ffb4ab
color2 #c9bfff
color3 #c9bfff
color4 #f8b1dd
color5 #c9bfff
color6 #c9bfff
color7 #f2dde7
color8 #a58999
color9 #ffb4ab
color10 #c9bfff
color11 #c9bfff
color12 #f8b1dd
color13 #c9bfff
color14 #c9bfff
color15 #f2dde7

cursor                #f2dde7
cursor_text_color     #1b1017
background            #1b1017
foreground            #f2dde7
selection_foreground  #ddbecf
selection_background  #57404e
active_border_color   #c9bfff
inactive_border_color #57404e
url_color             #c9bfff

active_tab_foreground   #302175
active_tab_background   #c9bfff
inactive_tab_foreground #ddbecf
inactive_tab_background #57404e
cursor_trail_color      #ddbecf
